"""TheDogAPI 견종 데이터의 한글 번역 사전 (사람이 작성, 오역 검수용).

- ADJ_KO: 기질 형용사(영문 소문자) → 자연스러운 한글. TheDogAPI 전체에서 쓰인 고유 형용사 전부 수록.
- NAME_KO: 견종명(TheDogAPI 'name' 원문) → 한글명. 표준 한글명이 있으면 그대로,
  없으면 외래어 표기법에 따른 음역.

ingest_breeds.py가 이 사전으로 번역하고, 크기는 체중에서, 체질은 한글명에서 파생한다.
"""
from __future__ import annotations

# ── 기질 형용사 → 한글 (키는 소문자) ─────────────────────────────────────────
ADJ_KO: dict[str, str] = {
    "adaptable": "적응력이 좋은",
    "affectionate": "다정한",
    "agile": "민첩한",
    "alert": "기민한",
    "aloof": "낯을 가리는",
    "amiable": "붙임성 있는",
    "athletic": "활동적인",
    "calm": "차분한",
    "cautious": "조심성 있는",
    "charming": "매력적인",
    "cheerful": "밝은",
    "confident": "자신감 있는",
    "courageous": "용감한",
    "curious": "호기심 많은",
    "determined": "의지가 강한",
    "devoted": "헌신적인",
    "dignified": "기품 있는",
    "docile": "온순한",
    "eager to please": "주인을 따르려는",
    "easygoing": "느긋한",
    "energetic": "에너지 넘치는",
    "even-tempered": "침착한",
    "fearless": "겁이 없는",
    "friendly": "친근한",
    "gentle": "온화한",
    "good-natured": "성격이 좋은",
    "happy": "명랑한",
    "hardy": "강건한",
    "independent": "독립적인",
    "intelligent": "영리한",
    "lively": "활발한",
    "loyal": "충성스러운",
    "merry": "쾌활한",
    "mischievous": "짓궂은",
    "optimistic": "낙천적인",
    "outgoing": "외향적인",
    "patient": "인내심 있는",
    "playful": "장난기 많은",
    "protective": "보호 본능이 강한",
    "reserved": "내성적인",
    "sensitive": "예민한",
    "smart": "똑똑한",
    "spirited": "기운찬",
    "tenacious": "끈기 있는",
    "variable depending on ancestry and individual traits": "혈통과 개체에 따라 다양한",
    "work-focused": "작업 집중력이 높은",
}

# ── 견종명 → 한글 ────────────────────────────────────────────────────────────
NAME_KO: dict[str, str] = {
    "Affenpinscher": "아펜핀셔",
    "Afghan Hound": "아프간 하운드",
    "Africanis": "아프리카니스",
    "Aidi": "아이디",
    "Airedale Terrier": "에어데일 테리어",
    "Airedoodle": "에어두들",
    "Akbash": "아크바시",
    "Akita": "아키타",
    "Aksaray Malaklisi": "아크사라이 말라클리시",
    "Alano Español": "알라노 에스파뇰",
    "Alapaha Blue Blood Bulldog": "알라파하 블루 블러드 불독",
    "Alaskan Husky": "알래스칸 허스키",
    "Alaskan Klee Kai": "알래스칸 클리 카이",
    "Alaskan Malamute": "알래스칸 맬러뮤트",
    "Alopekis": "알로페키스",
    "Alpine Dachsbracke": "알파인 닥스브라케",
    "American Bulldog": "아메리칸 불독",
    "American Bully": "아메리칸 불리",
    "American Cocker Spaniel": "아메리칸 코커 스패니얼",
    "American English Coonhound": "아메리칸 잉글리시 쿤하운드",
    "American Eskimo Dog": "아메리칸 에스키모 도그",
    "American Foxhound": "아메리칸 폭스하운드",
    "American Hairless Terrier": "아메리칸 헤어리스 테리어",
    "American Leopard Hound": "아메리칸 레오파드 하운드",
    "American Pit Bull Terrier": "아메리칸 핏불 테리어",
    "American Staffordshire Terrier": "아메리칸 스태퍼드셔 테리어",
    "American Water Spaniel": "아메리칸 워터 스패니얼",
    "Andalusian Terrier": "안달루시안 테리어",
    "Anglo-Français de Petite Vénerie": "앙글로 프랑세 드 프티 베네리",
    "Appenzeller Sennenhund": "아펜젤러 제넨훈트",
    "Argentine Pila": "아르헨티노 필라",
    "Ariégeois": "아리에주아",
    "Ariège Pointer": "아리에주 포인터",
    "Armant": "아르만트",
    "Armenian Gampr": "아르메니안 감프르",
    "Artois Hound": "아르투아 하운드",
    "Aussiedoodle": "오시두들",
    "Australian Cattle Dog": "오스트레일리안 캐틀 도그",
    "Australian Kelpie": "오스트레일리안 켈피",
    "Australian Shepherd": "오스트레일리안 셰퍼드",
    "Australian Silky Terrier": "오스트레일리안 실키 테리어",
    "Australian Stumpy Tail Cattle Dog": "오스트레일리안 스텀피 테일 캐틀 도그",
    "Australian Terrier": "오스트레일리안 테리어",
    "Austrian Black and Tan Hound": "오스트리안 블랙 앤 탄 하운드",
    "Austrian Pinscher": "오스트리안 핀셔",
    "Azawakh": "아자와크",
    "Bắc Hà": "박하",
    "Bakharwal Dog": "바카르왈 도그",
    "Banjara Hound": "반자라 하운드",
    "Bankhar Dog": "방하르 도그",
    "Barak Hound": "바라크 하운드",
    "Barbado da Terceira": "바르바도 다 테르세이라",
    "Barbet": "바르베",
    "Basenji": "바센지",
    "Basque Shepherd Dog": "바스크 셰퍼드 도그",
    "Bassador": "바사도르",
    "Basset Artésien Normand": "바세 아르테지앵 노르망",
    "Basset Bleu de Gascogne": "바세 블루 드 가스코뉴",
    "Basset Fauve de Bretagne": "바세 포브 드 브르타뉴",
    "Basset Hound": "바셋 하운드",
    "Bassettoodle": "바셋두들",
    "Bavarian Mountain Hound": "바이에른 마운틴 하운드",
    "Beagle": "비글",
    "Beagle-Harrier": "비글 해리어",
    "Bearded Collie": "비어디드 콜리",
    "Beauceron": "보스롱",
    "Bedlington Terrier": "베들링턴 테리어",
    "Belgian Laekenois": "벨지안 라케노이즈",
    "Belgian Malinois": "벨지안 말리노이즈",
    "Belgian Shepherd": "벨지안 셰퍼드",
    "Belgian Tervuren": "벨지안 테뷰런",
    "Bergamasco Sheepdog": "베르가마스코 십도그",
    "Berger Picard": "베르제 피카르",
    "Bernedoodle": "버니두들",
    "Bernese Mountain Dog": "버니즈 마운틴 도그",
    "Bichon Frisé": "비숑 프리제",
    "Biewer Terrier": "비버 테리어",
    "Billy": "빌리",
    "Black and Tan Coonhound": "블랙 앤 탄 쿤하운드",
    "Black Mouth Cur": "블랙 마우스 커",
    "Black Norwegian Elkhound": "블랙 노르위전 엘크하운드",
    "Black Russian Terrier": "블랙 러시안 테리어",
    "Bloodhound": "블러드하운드",
    "Blue Picardy Spaniel": "블루 피카르디 스패니얼",
    "Bluetick Coonhound": "블루틱 쿤하운드",
    "Boerboel": "보어부얼",
    "Bohemian Shepherd": "보헤미안 셰퍼드",
    "Bohemian Spotted Dog": "보헤미안 스포티드 도그",
    "Bolognese": "볼로네즈",
    "Border Collie": "보더 콜리",
    "Border Terrier": "보더 테리어",
    "Bordoodle": "보더두들",
    "Borzoi": "보르조이",
    "Boston Terrier": "보스턴 테리어",
    "Bouvier des Ardennes": "부비에 데 아르덴",
    "Bouvier des Flandres": "부비에 데 플랑드르",
    "Boxer": "복서",
    "Boxerdoodle": "복서두들",
    "Boykin Spaniel": "보이킨 스패니얼",
    "Bracco Italiano": "브라코 이탈리아노",
    "Braque d'Auvergne": "브라크 도베르뉴",
    "Braque du Bourbonnais": "브라크 뒤 부르보네",
    "Braque Français": "브라크 프랑세",
    "Braque Saint-Germain": "브라크 생제르맹",
    "Brazilian Terrier": "브라질리안 테리어",
    "Briard": "브리아드",
    "Briquet de Provence": "브리케 드 프로방스",
    "Briquet Griffon Vendéen": "브리케 그리퐁 방데앵",
    "Brittany": "브리타니",
    "Brittanydoodle": "브리타니두들",
    "Broholmer": "브로홀머",
    "Bruno Jura Hound": "브루노 쥐라 하운드",
    "Bucovina Shepherd Dog": "부코비나 셰퍼드 도그",
    "Bugg": "버그",
    "Bulgarian Hound": "불가리안 하운드",
    "Bulgarian Scenthound": "불가리안 센트하운드",
    "Bull Arab": "불 아랍",
    "Bulldog": "불독",
    "Bullmastiff": "불마스티프",
    "Bulloxer": "불록서",
    "Bull Terrier": "불 테리어",
    "Bull Terrier (Miniature)": "불 테리어 (미니어처)",
    "Bully Kutta": "불리 쿠타",
    "Burgos Pointer": "부르고스 포인터",
    "Ca de Bou": "카 데 보우",
    "Cairn Terrier": "케언 테리어",
    "Calupoh": "칼루포",
    "Ca Mè Mallorquí": "카 메 마요르키",
    "Campeiro Bulldog": "캄페이루 불독",
    "Canaan Dog": "가나안 도그",
    "Canadian Eskimo Dog": "캐나디안 에스키모 도그",
    "Can de Chira": "칸 데 치라",
    "Can de Palleiro": "칸 데 팔레이로",
    "Cane Corso": "케인 코르소",
    "Cane di Oropa": "카네 디 오로파",
    "Cane Paratore": "카네 파라토레",
    "Cantabrian Water Dog": "칸타브리안 워터 도그",
    "Cão de Gado Transmontano": "캉 드 가두 트란스몬타누",
    "Ca Rater Mallorquí": "카 라테르 마요르키",
    "Cardigan Welsh Corgi": "카디건 웰시 코기",
    "Carea Leonés": "카레아 레오네스",
    "Carolina Dog": "캐롤라이나 도그",
    "Carpathian Shepherd Dog": "카르파티안 셰퍼드 도그",
    "Castro Laboreiro Dog": "카스트루 라보레이루 도그",
    "Catahoula Leopard Dog": "카타훌라 레오파드 도그",
    "Catalan Sheepdog": "카탈란 십도그",
    "Caucasian Shepherd Dog": "카프카스 셰퍼드 도그",
    "Cavalier King Charles Spaniel": "카발리에 킹 찰스 스패니얼",
    "Cavapom": "카바폼",
    "Cavapoo": "카바푸",
    "Central Asian Shepherd Dog": "센트럴 아시안 셰퍼드 도그",
    "Český fousek": "체스키 포우세크",
    "Cesky Terrier": "체스키 테리어",
    "Chart Polski": "하르트 폴스키",
    "Chesapeake Bay Retriever": "체서피크 베이 리트리버",
    "Chien Français Blanc et Noir": "시앵 프랑세 블랑 에 누아르",
    "Chien Français Blanc et Orange": "시앵 프랑세 블랑 에 오랑주",
    "Chien Français Tricolore": "시앵 프랑세 트리콜로르",
    "Chihuahua": "치와와",
    "Chilean Terrier": "칠레안 테리어",
    "Chinese Crested": "차이니즈 크레스티드",
    "Chinese Shar-Pei": "차이니즈 샤페이",
    "Chinook": "치누크",
    "Chipoo": "치푸",
    "Chippiparai": "치피파라이",
    "Chiweenie": "치위니",
    "Chongqing Dog": "충칭 도그",
    "Chorkie": "초키",
    "Chortai": "초르타이",
    "Chow Chow": "차우차우",
    "Chug": "청",
    "Chukotka Sled Dog": "추콧카 슬레드 도그",
    "Cimarrón Uruguayo": "시마론 우루과요",
    "Cirneco dell'Etna": "치르네코 델레트나",
    "Clumber Spaniel": "클럼버 스패니얼",
    "Cockapoo": "코카푸",
    "Cocker Spaniel": "코커 스패니얼",
    "Colombian Fino Hound": "콜롬비안 피노 하운드",
    "Continental Bulldog": "콘티넨탈 불독",
    "Corgipoo": "코기푸",
    "Corsican Dog": "코르시칸 도그",
    "Coton de Tulear": "코통 드 튈레아르",
    "Cretan Hound": "크레탄 하운드",
    "Croatian Sheepdog": "크로아티안 십도그",
    "Curly-Coated Retriever": "컬리 코티드 리트리버",
    "Czechoslovakian Wolfdog": "체코슬로바키안 울프독",
    "Dachshund": "닥스훈트",
    "Dalmadoodle": "달마두들",
    "Dalmatian": "달마시안",
    "Dandie Dinmont Terrier": "댄디 딘몬트 테리어",
    "Danish Spitz": "데니시 스피츠",
    "Danish-Swedish Farmdog": "데니시 스웨디시 팜독",
    "Denmark Feist": "덴마크 파이스트",
    "Dikkulak": "디쿨라크",
    "Dingo": "딩고",
    "Doberman Pinscher": "도베르만 핀셔",
    "Dogo Argentino": "도고 아르헨티노",
    "Dogo Sardesco": "도고 사르데스코",
    "Dogue Brasileiro": "도그 브라질레이루",
    "Dogue de Bordeaux": "도그 드 보르도",
    "Donggyeongi": "동경이",
    "Dorkie": "도키",
    "Doxiepoo": "독시푸",
    "Drentse Patrijshond": "드렌체 파트레이스혼트",
    "Drever": "드레버",
    "Dunker": "둔커",
    "Dutch Shepherd": "더치 셰퍼드",
    "Dutch Smoushond": "더치 스마우스혼트",
    "East European Shepherd": "이스트 유러피안 셰퍼드",
    "East Siberian Laika": "이스트 시베리안 라이카",
    "Ecuadorian Hairless Dog": "에콰도리안 헤어리스 도그",
    "English Cocker Spaniel": "잉글리시 코커 스패니얼",
    "English Foxhound": "잉글리시 폭스하운드",
    "English Mastiff": "잉글리시 마스티프",
    "English Setter": "잉글리시 세터",
    "English Shepherd": "잉글리시 셰퍼드",
    "English Springer Spaniel": "잉글리시 스프링거 스패니얼",
    "English Toy Terrier (Black & Tan)": "잉글리시 토이 테리어 (블랙 앤 탄)",
    "Entlebucher Mountain Dog": "엔틀레부허 마운틴 도그",
    "Erbi Txakur": "에르비 차쿠르",
    "Eskapoo": "에스카푸",
    "Estonian Hound": "에스토니안 하운드",
    "Estrela Mountain Dog": "에스트렐라 마운틴 도그",
    "Eurasier": "오이라지어",
    "Faroese Sheepdog": "페로이즈 십도그",
    "Field Spaniel": "필드 스패니얼",
    "Fila Brasileiro": "필라 브라질레이루",
    "Finnish Hound": "피니시 하운드",
    "Finnish Lapphund": "피니시 라프훈드",
    "Finnish Spitz": "피니시 스피츠",
    "Flat-Coated Retriever": "플랫 코티드 리트리버",
    "Florida Cracker Cur": "플로리다 크래커 커",
    "Foxhoodle": "폭스후들",
    "French Bulldog": "프렌치 불독",
    "French Spaniel": "프렌치 스패니얼",
    "Frenchton": "프렌치턴",
    "Frug": "프러그",
    "Gascon Saintongeois": "가스콩 생통주아",
    "Gaucho Sheepdog": "가우초 십도그",
    "Georgian Shepherd": "조지안 셰퍼드",
    "Gerberian Shepsky": "거베리안 솁스키",
    "German Hound": "저먼 하운드",
    "German Longhaired Pointer": "저먼 롱헤어드 포인터",
    "German Pinscher": "저먼 핀셔",
    "German Roughhaired Pointer": "저먼 러프헤어드 포인터",
    "German Shepherd": "저먼 셰퍼드",
    "German Sheprador": "저먼 셰프라도르",
    "German Shorthaired Pointer": "저먼 쇼트헤어드 포인터",
    "German Spaniel": "저먼 스패니얼",
    "German Spitz": "저먼 스피츠",
    "German Wirehaired Pointer": "저먼 와이어헤어드 포인터",
    "Giant Schnauzer": "자이언트 슈나우저",
    "Glen of Imaal Terrier": "글렌 오브 이말 테리어",
    "Goberian": "고베리안",
    "Goldendoodle": "골든두들",
    "Golden Mountain Dog": "골든 마운틴 도그",
    "Golden Retriever": "골든 리트리버",
    "Gończy Polski": "곤치 폴스키",
    "Gordon Setter": "고든 세터",
    "Grand Anglo-Français Blanc et Noir": "그랑 앙글로 프랑세 블랑 에 누아르",
    "Grand Anglo-Français Blanc et Orange": "그랑 앙글로 프랑세 블랑 에 오랑주",
    "Grand Anglo-Français Tricolore": "그랑 앙글로 프랑세 트리콜로르",
    "Grand Basset Griffon Vendéen": "그랑 바세 그리퐁 방데앵",
    "Grand Bleu de Gascogne": "그랑 블루 드 가스코뉴",
    "Grand Griffon Vendéen": "그랑 그리퐁 방데앵",
    "Great Dane": "그레이트 데인",
    "Greater Swiss Mountain Dog": "그레이터 스위스 마운틴 도그",
    "Greek Harehound": "그릭 헤어하운드",
    "Greek Shepherd": "그릭 셰퍼드",
    "Greenland Dog": "그린란드 도그",
    "Greyhound": "그레이하운드",
    "Griffon Bleu de Gascogne": "그리퐁 블루 드 가스코뉴",
    "Griffon Bruxellois": "그리퐁 브뤼셀루아",
    "Griffon Fauve de Bretagne": "그리퐁 포브 드 브르타뉴",
    "Griffon Nivernais": "그리퐁 니베르네",
    "Gull Dong": "굴 동",
    "Gull Terrier": "굴 테리어",
    "Halden Hound": "할덴 하운드",
    "Hällefors Elkhound": "핼레포르스 엘크하운드",
    "Hamiltonstövare": "하밀톤스퇴바레",
    "Hanoverian Scenthound": "하노베리안 센트하운드",
    "Harrier": "해리어",
    "Havanese": "하바니즈",
    "Havapoo": "하바푸",
    "Himalayan Sheepdog": "히말라얀 십도그",
    "Hmong Bobtail Dog": "몽 밥테일 도그",
    "Hokkaido": "홋카이도",
    "Hovawart": "호바바르트",
    "Huntaway": "헌터웨이",
    "Huskimo": "허스키모",
    "Hygen Hound": "휘겐 하운드",
    "Ibizan Hound": "이비전 하운드",
    "Icelandic Sheepdog": "아이슬란딕 십도그",
    "Indian Pariah Dog": "인디안 파리아 도그",
    "Indian Spitz": "인디안 스피츠",
    "Irish Doodle": "아이리시 두들",
    "Irish Red and White Setter": "아이리시 레드 앤 화이트 세터",
    "Irish Setter": "아이리시 세터",
    "Irish Terrier": "아이리시 테리어",
    "Irish Water Spaniel": "아이리시 워터 스패니얼",
    "Irish Wolfhound": "아이리시 울프하운드",
    "Istrian Coarse-haired Hound": "이스트리안 코스헤어드 하운드",
    "Istrian Shorthaired Hound": "이스트리안 쇼트헤어드 하운드",
    "Italian Greyhound": "이탈리안 그레이하운드",
    "Jack Russell Terrier": "잭 러셀 테리어",
    "Jagdterrier": "약트테리어",
    "Jämthund": "옘트훈드",
    "Japanese Chin": "재패니즈 친",
    "Japanese Spitz": "재패니즈 스피츠",
    "Japanese Terrier": "재패니즈 테리어",
    "Jeju Dog": "제주개",
    "Jindo": "진돗개",
    "Jonangi": "조낭기",
    "Kaikadi": "카이카디",
    "Kai Ken": "카이 켄",
    "Kamchatka Sled Dog": "캄차카 슬레드 도그",
    "Kangal Shepherd Dog": "캉갈 셰퍼드 도그",
    "Kanni": "칸니",
    "Karakachan": "카라카찬",
    "Karelian Bear Dog": "카렐리안 베어 도그",
    "Karelo-Finnish Laika": "카렐로 피니시 라이카",
    "Kars": "카르스",
    "Karst Shepherd": "카르스트 셰퍼드",
    "Kazakh Tazy": "카자흐 타지",
    "Keeshond": "키스혼드",
    "Kerry Beagle": "케리 비글",
    "Kerry Blue Terrier": "케리 블루 테리어",
    "Khala": "칼라",
    "King Charles Spaniel": "킹 찰스 스패니얼",
    "King Shepherd": "킹 셰퍼드",
    "Kintamani": "킨타마니",
    "Kishu Ken": "기슈 켄",
    "Kokoni": "코코니",
    "Kombai": "콤바이",
    "Komondor": "코몬도르",
    "Kooikerhondje": "코이커혼제",
    "Koolie": "쿨리",
    "Kromfohrländer": "크롬포를랜더",
    "Kuchi": "쿠치",
    "Kunming Dog": "쿤밍 도그",
    "Kurdish Mastiff": "쿠르드 마스티프",
    "Kuvasz": "쿠바스",
    "Labradoodle": "래브라두들",
    "Labrador Retriever": "래브라도 리트리버",
    "Labraheeler": "래브라힐러",
    "Labsky": "랩스키",
    "Lacy Dog": "레이시 도그",
    "Lagotto Romagnolo": "라고토 로마뇰로",
    "Lài": "라이",
    "Laizhou Hong": "라이저우 훙",
    "Lakeland Terrier": "레이클랜드 테리어",
    "Lancashire Heeler": "랭커셔 힐러",
    "Landseer": "랜드시어",
    "Langqing": "랑칭",
    "Lapponian Herder": "라포니안 허더",
    "Large Münsterländer": "라지 뮌스터랜더",
    "Leonberger": "레온베르거",
    "Levriero Sardo": "레브리에로 사르도",
    "Lhasa Apso": "라사 압소",
    "Lhasapoo": "라사푸",
    "Liangshan Dog": "량산 도그",
    "Lithuanian Hound": "리투아니안 하운드",
    "Lobito Herreño": "로비토 에레뇨",
    "Löwchen": "뢰브헨",
    "Lucas Terrier": "루카스 테리어",
    "Lupo Italiano": "루포 이탈리아노",
    "Lurcher": "러처",
    "Mackenzie River Husky": "매켄지 리버 허스키",
    "Magyar Agár": "머저르 어가르",
    "Mahratta Hound": "마라타 하운드",
    "Majorca Shepherd Dog": "마요르카 셰퍼드 도그",
    "Maltese": "말티즈",
    "Maltipoo": "말티푸",
    "Maltshi": "말티시",
    "Manchester Terrier": "맨체스터 테리어",
    "Maneto": "마네토",
    "Maremma Sheepdog": "마렘마 십도그",
    "Markiesje": "마르키셰",
    "Mastidoodle": "마스티두들",
    "McNab": "맥납",
    "Miniature American Shepherd": "미니어처 아메리칸 셰퍼드",
    "Miniature Bull Terrier": "미니어처 불 테리어",
    "Miniature Fox Terrier": "미니어처 폭스 테리어",
    "Miniature Pinscher": "미니어처 핀셔",
    "Miniature Schnauzer": "미니어처 슈나우저",
    "Mojee": "모지",
    "Molossus of Epirus": "몰로서스 오브 에피루스",
    "Mongrel": "믹스견",
    "Montenegrin Mountain Hound": "몬테네그린 마운틴 하운드",
    "Morkie": "모키",
    "Moscow Watchdog": "모스크바 워치독",
    "Mountain Cur": "마운틴 커",
    "Mountain Feist": "마운틴 파이스트",
    "Mudhol Hound": "무돌 하운드",
    "Mudi": "무디",
    "Neapolitan Mastiff": "네아폴리탄 마스티프",
    "Nenets Herding Laika": "네네츠 허딩 라이카",
    "Newfoundland": "뉴펀들랜드",
    "Newfypoo": "뉴피푸",
    "New Guinea Singing Dog": "뉴기니 싱잉 도그",
    "New Zealand Heading Dog": "뉴질랜드 헤딩 도그",
    "Norfolk Terrier": "노퍽 테리어",
    "Norrbottenspets": "노르보텐스페츠",
    "Northern Inuit Dog": "노던 이누이트 도그",
    "Norwegian Buhund": "노르위전 부훈드",
    "Norwegian Elkhound": "노르위전 엘크하운드",
    "Norwegian Lundehund": "노르위전 룬데훈드",
    "Norwich Terrier": "노리치 테리어",
    "Nova Scotia Duck Tolling Retriever": "노바스코샤 덕 톨링 리트리버",
    "Nureongi": "누렁이",
    "Old Danish Pointer": "올드 데니시 포인터",
    "Olde English Bulldogge": "올드 잉글리시 불도그",
    "Old English Sheepdog": "올드 잉글리시 십도그",
    "Otterhound": "오터하운드",
    "Pachón Navarro": "파촌 나바로",
    "Pampas Deerhound": "팜파스 디어하운드",
    "Papillon": "파피용",
    "Papipoo": "파피푸",
    "Parson Russell Terrier": "파슨 러셀 테리어",
    "Pastore della Lessinia e del Lagorai": "파스토레 델라 레시니아 에 델 라고라이",
    "Pastor Garafiano": "파스토르 가라피아노",
    "Patagonian Sheepdog": "파타고니안 십도그",
    "Patterdale Terrier": "패터데일 테리어",
    "Peekapoo": "피카푸",
    "Pekeapoo": "피키푸",
    "Pekingese": "페키니즈",
    "Pembroke Welsh Corgi": "펨브로크 웰시 코기",
    "Perdigueiro Galego": "페르디게이루 갈레구",
    "Perro Majorero": "페로 마호레로",
    "Peruvian Inca Orchid": "페루비안 잉카 오키드",
    "Petit Basset Griffon Vendéen": "프티 바세 그리퐁 방데앵",
    "Petit Bleu de Gascogne": "프티 블루 드 가스코뉴",
    "Phalène": "팔렌",
    "Pharaoh Hound": "파라오 하운드",
    "Philippine Forest Dog": "필리핀 포레스트 도그",
    "Phu Quoc Ridgeback": "푸꾸옥 리지백",
    "Picardy Spaniel": "피카르디 스패니얼",
    "Pitsky": "핏스키",
    "Plott Hound": "플롯 하운드",
    "Plummer Terrier": "플러머 테리어",
    "Podenco Andaluz": "포덴코 안달루스",
    "Podenco Canario": "포덴코 카나리오",
    "Podenco Valenciano": "포덴코 발렌시아노",
    "Pointer": "포인터",
    "Poitevin": "푸아트뱅",
    "Polish Hound": "폴리시 하운드",
    "Polish Lowland Sheepdog": "폴리시 로랜드 십도그",
    "Pomapoo": "포마푸",
    "Pomeranian": "포메라니안",
    "Pomsky": "폼스키",
    "Pont-Audemer Spaniel": "퐁토드메르 스패니얼",
    "Poochon": "푸촌",
    "Poodle": "푸들",
    "Poodle (Miniature)": "푸들 (미니어처)",
    "Poodle (Toy)": "푸들 (토이)",
    "Porcelaine": "포르슬렌",
    "Portuguese Podengo": "포르투기즈 포덴고",
    "Portuguese Pointer": "포르투기즈 포인터",
    "Portuguese Sheepdog": "포르투기즈 십도그",
    "Portuguese Water Dog": "포르투기즈 워터 도그",
    "Posavac Hound": "포사바츠 하운드",
    "Pražský Krysařík": "프라슈스키 크리사르지크",
    "Presa Canario": "프레사 카나리오",
    "Pudelpointer": "푸델포인터",
    "Pug": "퍼그",
    "Pugapoo": "퍼가푸",
    "Puggle": "퍼글",
    "Puli": "풀리",
    "Pumi": "푸미",
    "Pungsan": "풍산개",
    "Pyredoodle": "파이어두들",
    "Pyrenean Mastiff": "피레니안 마스티프",
    "Pyrenean Mountain Dog": "피레니안 마운틴 도그",
    "Pyrenean Sheepdog": "피레니안 십도그",
    "Rafeiro do Alentejo": "하페이루 두 알렌테주",
    "Rajapalayam": "라자팔라얌",
    "Rampur Greyhound": "람푸르 그레이하운드",
    "Rastreador Brasileiro": "하스트레아도르 브라질레이루",
    "Ratonero Murciano": "라토네로 무르시아노",
    "Rat Terrier": "랫 테리어",
    "Redbone Coonhound": "레드본 쿤하운드",
    "Rhodesian Ridgeback": "로디지안 리지백",
    "Ridgeypoo": "리지푸",
    "Rize Koyun": "리제 코윤",
    "Romanian Mioritic Shepherd Dog": "루마니안 미오리틱 셰퍼드 도그",
    "Romanian Raven Shepherd Dog": "루마니안 레이븐 셰퍼드 도그",
    "Rottle": "로틀",
    "Rottsky": "롯스키",
    "Rottweiler": "로트와일러",
    "Rough Collie": "러프 콜리",
    "Russian Spaniel": "러시안 스패니얼",
    "Russian Toy": "러시안 토이",
    "Russo-European Laika": "루소 유러피안 라이카",
    "Ryukyu": "류큐",
    "Saarloos Wolfdog": "사를로스 울프독",
    "Sabueso Español": "사부에소 에스파뇰",
    "Saint Berdoodle": "세인트 버두들",
    "Saint Bernard": "세인트 버나드",
    "Saint Miguel Cattle Dog": "세인트 미겔 캐틀 도그",
    "Saint-Usuge Spaniel": "생튀쥐주 스패니얼",
    "Sakhalin Husky": "사할린 허스키",
    "Saluki": "살루키",
    "Samoyed": "사모예드",
    "Sapsali": "삽살개",
    "Sarabi": "사라비",
    "Sarail Hound": "사라일 하운드",
    "Sardinian Shepherd Dog": "사르데냐 셰퍼드 도그",
    "Šarplaninac": "샤르플라니나츠",
    "Schapendoes": "스하펜두스",
    "Schillerstövare": "실레르스퇴바레",
    "Schipperke": "스키퍼키",
    "Schnoodle": "슈누들",
    "Schweizerischer Niederlaufhund": "슈바이처리셔 니더라우프훈트",
    "Schweizer Laufhund": "슈바이처 라우프훈트",
    "Scoodle": "스쿠들",
    "Scottish Deerhound": "스코티시 디어하운드",
    "Scottish Terrier": "스코티시 테리어",
    "Sealyham Terrier": "실리엄 테리어",
    "Segugio dell'Appennino": "세구조 델라페니노",
    "Segugio Italiano": "세구조 이탈리아노",
    "Segugio Maremmano": "세구조 마렘마노",
    "Serbian Hound": "세르비안 하운드",
    "Serbian Tricolour Hound": "세르비안 트라이컬러 하운드",
    "Serrano Bulldog": "세하누 불독",
    "Sheepadoodle": "십어두들",
    "Shetland Sheepdog": "셰틀랜드 십도그",
    "Shiba Inu": "시바 이누",
    "Shih Poo": "시추푸",
    "Shih Tzu": "시츄",
    "Shikoku": "시코쿠",
    "Shiloh Shepherd": "실로 셰퍼드",
    "Shorkie": "쇼키",
    "Siberian Husky": "시베리안 허스키",
    "Silken Windhound": "실켄 윈드하운드",
    "Sinhala Hound": "신할라 하운드",
    "Skye Terrier": "스카이 테리어",
    "Sloughi": "슬루기",
    "Slovak Cuvac": "슬로바크 추바츠",
    "Slovak Rough-haired Pointer": "슬로바크 러프헤어드 포인터",
    "Slovenský kopov": "슬로벤스키 코포프",
    "Smaland Hound": "스몰란드 하운드",
    "Small Međimurje Dog": "스몰 메지무레 도그",
    "Small Münsterländer": "스몰 뮌스터랜더",
    "Smithfield": "스미스필드",
    "Smooth Collie": "스무드 콜리",
    "Smooth Fox Terrier": "스무드 폭스 테리어",
    "Soft Coated Wheaten Terrier": "소프트 코티드 휘튼 테리어",
    "Spanish Greyhound": "스패니시 그레이하운드",
    "Spanish Mastiff": "스패니시 마스티프",
    "Spanish Water Dog": "스패니시 워터 도그",
    "Spino degli Iblei": "스피노 델리 이블레이",
    "Spinone Italiano": "스피노네 이탈리아노",
    "Sporting Lucas Terrier": "스포팅 루카스 테리어",
    "Springerdoodle": "스프링거두들",
    "Sprollie": "스프롤리",
    "Stabyhoun": "스타비훈",
    "Staffordshire Bull Terrier": "스태퍼드셔 불 테리어",
    "Standard Schnauzer": "스탠더드 슈나우저",
    "Stephens Stock": "스티븐스 스톡",
    "St. Hubert Jura Hound": "생튀베르 쥐라 하운드",
    "Styrian Coarse-haired Hound": "슈타이리안 코스헤어드 하운드",
    "Sussex Spaniel": "서식스 스패니얼",
    "Swedish Lapphund": "스웨디시 라프훈드",
    "Swedish Vallhund": "스웨디시 발훈드",
    "Taigan": "타이간",
    "Taiwan Dog": "타이완 도그",
    "Tamaskan Dog": "타마스칸 도그",
    "Tang Dog": "탕 도그",
    "Tarsus Çatalburun": "타르수스 차탈부룬",
    "Tatra Shepherd Dog": "타트라 셰퍼드 도그",
    "Teddy Roosevelt Terrier": "테디 루스벨트 테리어",
    "Telomian": "텔로미안",
    "Tenterfield Terrier": "텐터필드 테리어",
    "Thai Bangkaew Dog": "타이 방깨우 도그",
    "Thai Ridgeback": "타이 리지백",
    "Tibetan Kyi Apso": "티베탄 키 압소",
    "Tibetan Mastiff": "티베탄 마스티프",
    "Tibetan Spaniel": "티베탄 스패니얼",
    "Tibetan Terrier": "티베탄 테리어",
    "Tonya Finosu": "토니아 피노수",
    "Tornjak": "토르냐크",
    "Tosa": "도사견",
    "Tosa Ken": "도사 켄",
    "Toy Fox Terrier": "토이 폭스 테리어",
    "Toy Manchester Terrier": "토이 맨체스터 테리어",
    "Transylvanian Hound": "트란실바니안 하운드",
    "Treeing Cur": "트리잉 커",
    "Treeing Feist": "트리잉 파이스트",
    "Treeing Tennessee Brindle": "트리잉 테네시 브린들",
    "Treeing Walker Coonhound": "트리잉 워커 쿤하운드",
    "Trigg Hound": "트리그 하운드",
    "Tyrolean Hound": "티롤리안 하운드",
    "Valencian Terrier": "발렌시안 테리어",
    "Valley Bulldog": "밸리 불독",
    "Vikhan": "비칸",
    "Villano de Las Encartaciones": "비야노 데 라스 엔카르타시오네스",
    "Villanuco de Las Encartaciones": "비야누코 데 라스 엔카르타시오네스",
    "Vizsla": "비즐라",
    "Vizsladoodle": "비즐라두들",
    "Volkosob": "볼코소브",
    "Volpino Italiano": "볼피노 이탈리아노",
    "Weimaraner": "바이마라너",
    "Weimardoodle": "바이마두들",
    "Welsh Hound": "웰시 하운드",
    "Welsh Sheepdog": "웰시 십도그",
    "Welsh Springer Spaniel": "웰시 스프링거 스패니얼",
    "Welsh Terrier": "웰시 테리어",
    "West Country Harrier": "웨스트 컨트리 해리어",
    "West Highland White Terrier": "웨스트 하일랜드 화이트 테리어",
    "Westiepoo": "웨스티푸",
    "Westphalian Dachsbracke": "베스트팔리안 닥스브라케",
    "West Siberian Laika": "웨스트 시베리안 라이카",
    "Wetterhoun": "베터르훈",
    "Whippet": "휘핏",
    "White Shepherd": "화이트 셰퍼드",
    "White Swiss Shepherd Dog": "화이트 스위스 셰퍼드 도그",
    "Wire Fox Terrier": "와이어 폭스 테리어",
    "Wirehaired Pointing Griffon": "와이어헤어드 포인팅 그리퐁",
    "Wirehaired Vizsla": "와이어헤어드 비즐라",
    "Xiasi Dog": "샤시 도그",
    "Xigou": "시거우",
    "Xoloitzcuintli": "숄로이츠쿠인틀리",
    "Yakutian Laika": "야쿠티안 라이카",
    "Yorkipoo": "요키푸",
    "Yorkshire Terrier": "요크셔 테리어",
    "Yorktese": "요크티즈",
    "Zerdava": "제르다바",
}

# ── 한국에서 흔히 쓰는 약칭/별칭 → 카탈로그의 정식 영문명 ─────────────────────
# TheDogAPI에 없는 통칭(웰시코기)이나 변형 표기를 흔한 입력에서 잡아주기 위한 보강.
# 원본 영문 종의 번역 데이터를 그대로 복사해 별칭 키로도 적재한다.
ALIASES: dict[str, str] = {
    "웰시코기": "Pembroke Welsh Corgi",
    "코기": "Pembroke Welsh Corgi",
    "비숑": "Bichon Frisé",
    "시바견": "Shiba Inu",
    "포메": "Pomeranian",
    "미니핀": "Miniature Pinscher",
    "말라뮤트": "Alaskan Malamute",
    "허스키": "Siberian Husky",
    "리트리버": "Golden Retriever",
    "골든": "Golden Retriever",
    "토이푸들": "Poodle (Toy)",
    "미니어처푸들": "Poodle (Miniature)",
    "닥스훈트": "Dachshund",
    "차이니즈 크레스티드 독": "Chinese Crested",
}

# ── 크기 보정 (한국 반려 실태 기준) ──────────────────────────────────────────
# TheDogAPI 체중이 대형 표준 기준이라 한국에서 흔한 소형 변종과 어긋나는 경우만 교정.
SIZE_OVERRIDES: dict[str, str] = {
    "푸들": "small",   # 한국 반려 푸들은 대개 토이/미니어처(소형)
}
