"""initial schema

Revision ID: 96a7fd767f47
Revises: 
Create Date: 2026-06-19 16:47:25.724854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96a7fd767f47'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_email'), 'account', ['email'], unique=True)
    op.create_table('breed_catalog',
    sa.Column('breed', sa.String(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('temperament', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('breed')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=False)
    op.create_table('region',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_region_name'), 'region', ['name'], unique=False)
    op.create_table('barrier_free_facility',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('road_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barrier_free_facility_region_id'), 'barrier_free_facility', ['region_id'], unique=False)
    op.create_table('breed_catalog_trait',
    sa.Column('breed', sa.String(), nullable=False),
    sa.Column('trait', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['breed'], ['breed_catalog.breed'], ),
    sa.PrimaryKeyConstraint('breed', 'trait')
    )
    op.create_table('facility',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('road_address', sa.String(), nullable=True),
    sa.Column('jibun_address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('operating_hours', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facility_region_id'), 'facility', ['region_id'], unique=False)
    op.create_table('pet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('breed', sa.String(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('temperament', sa.String(), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('features', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pet_account_id'), 'pet', ['account_id'], unique=False)
    op.create_table('barrier_free_feature',
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('feature_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['barrier_free_facility.id'], ),
    sa.PrimaryKeyConstraint('facility_id', 'feature_code')
    )
    op.create_table('facility_allowed_pet_size',
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('pet_size', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.PrimaryKeyConstraint('facility_id', 'pet_size')
    )
    op.create_table('facility_pet_policy',
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('companion_allowed', sa.Boolean(), nullable=False),
    sa.Column('restriction', sa.String(), nullable=True),
    sa.Column('extra_fee', sa.String(), nullable=True),
    sa.Column('indoor', sa.Boolean(), nullable=False),
    sa.Column('outdoor', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.PrimaryKeyConstraint('facility_id')
    )
    op.create_table('pet_activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pet_activity_facility_id'), 'pet_activity', ['facility_id'], unique=False)
    op.create_index(op.f('ix_pet_activity_pet_id'), 'pet_activity', ['pet_id'], unique=False)
    op.create_table('pet_trait',
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('trait', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ),
    sa.PrimaryKeyConstraint('pet_id', 'trait')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet_trait')
    op.drop_index(op.f('ix_pet_activity_pet_id'), table_name='pet_activity')
    op.drop_index(op.f('ix_pet_activity_facility_id'), table_name='pet_activity')
    op.drop_table('pet_activity')
    op.drop_table('facility_pet_policy')
    op.drop_table('facility_allowed_pet_size')
    op.drop_table('barrier_free_feature')
    op.drop_index(op.f('ix_pet_account_id'), table_name='pet')
    op.drop_table('pet')
    op.drop_index(op.f('ix_facility_region_id'), table_name='facility')
    op.drop_table('facility')
    op.drop_table('breed_catalog_trait')
    op.drop_index(op.f('ix_barrier_free_facility_region_id'), table_name='barrier_free_facility')
    op.drop_table('barrier_free_facility')
    op.drop_index(op.f('ix_region_name'), table_name='region')
    op.drop_table('region')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_table('category')
    op.drop_table('breed_catalog')
    op.drop_index(op.f('ix_account_email'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
